#!/usr/bin/env zsh

setopt ERREXIT PIPEFAIL NOUNSET

CONFIG_FILE=${0:h}/i3status-rs.config.toml

if [[ ${commands[i3status-rs]} ]]; then
    exec i3status-rs $CONFIG_FILE
else
    printf "Could not find i3status-rs, exiting.\n" >&2
    exit 1
fi
